### ISSUE TITLE
Doesn't work with other shell themes

### ISSUE THREAD

**Issue by shihrer** [ipaq3870/gsext-transparent-notification#3]
Notifications aren't transparent with other shell themes.  I've tried Arc and Arc Dark so far.

**Comment by Vistaus** [comment]
Same here.

**Comment by miguelsan** [comment]
Try modifying `.local/share/gnome-shell/extensions/transparentnotification@ipaq3870/stylesheet.css` like this:

```css
.notification-transparency {
    background-color: rgba(0,0,0,0.5);
}

.notification-transparency * {
    color: rgba(247,247,247,1);
}
```
